version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.8
        environment:
          PIPENV_VENV_IN_PROJECT: true
      - image: circleci/postgres:10-alpine
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: surveys_api_test
          TEST_RESULTS: /tmp/test-results
          ENV: test
          DATABASE_USER: surveys_api
          DATABASE_NAME: surveys_api_test
          DATABASE_PASSWORD: surveys_api
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432

    working_directory: ~/circleci-demo-python-django

    steps:
      - checkout

      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1


      - run:
          command: mkdir -p /tmp/test-results

      - run:
          name: Pip Install
          command: |
            pip install -r requirements.txt
      #- run:
          #name: Database Setup
          #command: |
            #make install
      - run:
          name: Test
          command: |
            make test

      # Save artifacts
      - store_test_results:
          path: /tmp/test-results
