version: 2
jobs:
  build:
    working_directory: ~/surveys_api

    docker:
      - image: circleci/python:3.7.0-node-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: root
          DATABASE_NAME: surveys_api_test
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          DATABASE_USER: surveys_api
          DATABASE_PASSWORD:
          POSTGRES_DB: postgres
          POSTGRES_USER: root
      - image: circleci/postgres:10-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: surveys_api_test

    steps:
      - checkout
      - run:
          command: mkdir -p /tmp/test-results

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo pip3 install -Ur requirements.txt

      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost $DATABASE_PORT && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1

      - run:
          name: Database Setup
          command: |
            make db-create -i
            make db-migrate -i

      - run:
          name: Run unit tests
          command: |
            make test

      - store_test_results:
          path: /tmp/test-results
